TRUNCATE TABLE activity_evidences;
TRUNCATE TABLE activity_members;
TRUNCATE TABLE activity_outputs;
TRUNCATE TABLE approved_activities;
TRUNCATE TABLE approved_activities_audit;
TRUNCATE TABLE cycle;
TRUNCATE TABLE documents;
TRUNCATE TABLE capstone.group;
TRUNCATE TABLE groupdetails;
TRUNCATE TABLE  measurement;
TRUNCATE TABLE  measurement_audit;
TRUNCATE TABLE  measurements_activities;
TRUNCATE TABLE  measurements_activities_audit;
TRUNCATE TABLE  measurements_targets;
TRUNCATE TABLE  measurements_targets_audit;
TRUNCATE TABLE  metric;
TRUNCATE TABLE  pending_activities;
TRUNCATE TABLE  pending_activities_audit;
TRUNCATE TABLE  pending_outputs;
TRUNCATE TABLE  notifications;
TRUNCATE TABLE  notifications_read

